/**
 * Writes src/generated/nav.ts: the light metadata of every page (titles, hooks, scale, claim grades),
 * so menus, the ruler, the journey and /claims never have to bundle the full text of every page.
 * Run by `pnpm gen` after gen-data (the content imports the generated verses).
 */
import { writeFileSync } from "node:fs";
import type { Page } from "../src/content/define";
import { pages } from "../src/content/registry";

const entries = Object.values(pages).map((p: Page) => ({
  slug: p.slug,
  title: p.title,
  navTitle: p.navTitle,
  description: p.description,
  hook: p.hook,
  part: p.part,
  scale: p.scale,
  scene: p.scene,
  topics: p.flow.flatMap((b) => (b.kind === "topic" ? [{ id: b.id, title: b.title, status: b.status }] : [])),
}));

writeFileSync(
  new URL("../src/generated/nav.ts", import.meta.url),
  `// Generated by scripts/gen-nav.tsx from src/content/pages. Do not edit.
import type { NavEntry } from "@/content/nav-types";

export const NAV = ${JSON.stringify(entries, null, 1)} as const satisfies readonly NavEntry[];
`,
);
console.log(`gen: nav for ${entries.length} pages, ${entries.reduce((n, e) => n + e.topics.length, 0)} claims`);
